version: '3.3'
services:
  mysql:
    build:
      context: ./Clientes
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  app-clientes:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    restart: always
    depends_on:
      - mysql